### ISSUE TITLE
On windows, \ needs to be escaped in path name

### ISSUE THREAD

**Issue by scratchyone** [tversteeg/const-tweaker#3]
On windows the \ isn't escaped so you end up with `oninput="send('src\main.rs::VALUE', Number(this.value), 'f64')"`, which is an invalid path because the backslash escapes the m.

**Comment by tversteeg** [comment]
Thanks for the issue! I've made a commit to attempt to fix it, but I can't test it because I'm running on Linux. Could you verify if it works now?

**Comment by scratchyone** [comment]
It works perfectly now, thanks!
