### ISSUE TITLE
Const-tweaker-attribute as no license in the crate source

### ISSUE THREAD

**Issue by remilauzier** [tversteeg/const-tweaker#7]
Hi. That would help in packaging for fedora to have a license file include in the crate.

**Comment by tversteeg** [comment]
What do you mean exactly? I specified the license in `Cargo.toml` and it is also included in the crate?

**Comment by remilauzier** [comment]
I mean a file name LICENSE that would describe the specific license. Fedora take the description of the license in ``cargo.toml`` to mark the package, but they want to also include a copy of the license with the package. There is a copy in const-tweaker, but it is not in const-tweaker-attribute.

https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text

**Comment by tversteeg** [comment]
I see, so I should copy the file to that directory as well?

**Comment by remilauzier** [comment]
Yup. That should fix the problem. Cargo doesn't see what is not in is directory.
